apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-role-binding
subjects:
  - kind: ServiceAccount
    name: custom-service-account
    namespace: argo
roleRef:
  kind: Role
  name: custom-argo-role
  apiGroup: rbac.authorization.k8s.io