apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-argo-role
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "cronworkflows"]
    verbs: ["get", "list", "create", "watch"]